[2025-03-17 06:40:22] ERROR [celery.utils.dispatch.signal:280] Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7fac2f98c2e0>> raised: ModuleNotFoundError("No module named 'corsheaders'")
Traceback (most recent call last):
  File "/home/akh/.local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/akh/.local/lib/python3.8/site-packages/celery/fixups/django.py", line 97, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/akh/.local/lib/python3.8/site-packages/celery/fixups/django.py", line 135, in validate_models
    self.django_setup()
  File "/home/akh/.local/lib/python3.8/site-packages/celery/fixups/django.py", line 131, in django_setup
    django.setup()
  File "/home/akh/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/akh/.local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/akh/.local/lib/python3.8/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'
[2025-03-17 06:40:22] ERROR [celery.utils.dispatch.signal:280] Signal handler <promise@0x7fac2f8cf2c0 --> <bound method Celery._autodiscover_tasks of <Celery nobat at 0x7fac2f98c040>>> raised: AppRegistryNotReady("Apps aren't loaded yet.")
Traceback (most recent call last):
  File "/home/akh/.local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/akh/.local/lib/python3.8/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
  File "/home/akh/.local/lib/python3.8/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
  File "/home/akh/.local/lib/python3.8/site-packages/celery/app/base.py", line 692, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
  File "/home/akh/.local/lib/python3.8/site-packages/celery/app/base.py", line 701, in _autodiscover_tasks_from_fixups
    return self._autodiscover_tasks_from_names([
  File "/home/akh/.local/lib/python3.8/site-packages/celery/app/base.py", line 704, in <listcomp>
    for pkg in fixup.autodiscover_tasks()
  File "/home/akh/.local/lib/python3.8/site-packages/celery/fixups/django.py", line 107, in autodiscover_tasks
    return [config.name for config in apps.get_app_configs()]
  File "/home/akh/.local/lib/python3.8/site-packages/django/apps/registry.py", line 147, in get_app_configs
    self.check_apps_ready()
  File "/home/akh/.local/lib/python3.8/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
